(use srfi-27)
(define (square x) (* x x))
(define fermat-times 10)
(define (expmod base exp m)
	(cond
		((= exp 0) 1)
		((even? exp)
		 (remainder (square (expmod base (/ exp 2) m))
		 			m))
		(else
		 (remainder (* base (expmod base (- exp 1) m))
		 			m))))
(define (fermat-test n)
	(define (try-it a)
		(= (expmod a n n) a))
	(try-it (+ 1 (random-integer (- n 1)))))
(define (prime? n)
	(define (iter times)
		(cond
			((= times 0) #t)
			((fermat-test n) (iter (- times 1)))
			(else #f)))
	(iter fermat-times))
