(load "./fast-prime.scm")
(load "./runtime.scm")
(define (timed-prime-test n)
	(newline)
	(display n)
	(start-prime-test n (runtime))
)
(define (start-prime-test n start-time)
	(and (fast-prime? n 10)
		(report-prime (- (runtime) start-time))
	)
)
(define (report-prime elapsed-time)
	(display " *** ")
	(display elapsed-time)
	#t)
(define (search-for-primes start n)
	(define (search-inner counter rest)
		(if (= rest 0)
			#t
			(if (timed-prime-test counter)
				(search-inner (+ counter 1) (- rest 1))
				(search-inner (+ counter 1) rest))))
	(search-inner start n))
(define (square x) (* x x))

; main
(define (cube x) (* x x x))
(search-for-primes 1000 3)

;(search-for-primes 10000 3)
;(search-for-primes 100000 3)
(search-for-primes 1000000 3)
(search-for-primes (square (square (square 1000))) 3)
(search-for-primes (square (square (square (square 1000)))) 3)
(search-for-primes (square (square (square (square (square 1000))))) 3)
(search-for-primes (square (square (square (square (square (square 1000)))))) 3)
