(define dx 0.00001)
(define (compose f g)
	(lambda (x) (f (g x))))
(define (repeated f n)
	(define (iter i)
		(if (= i 1)
			f
			(compose f (iter (- i 1)))))
	(iter n))
(define (smooth f)
	(lambda (x)
		(/ (+	(f (- x dx))
				(f x)
				(f (+ x dx)))
		 3)))
(define (n-fold-smoothed f n)
	((repeated smooth n) f))
(define (inc x) (+ x 1))
(define (square x) (* x x))
(print ((n-fold-smoothed square 5) 10))

