(define (square x)
	(* x x))
(define (square-list1 items)
	(if (null? items)
		'()
		(cons (square (car items)) (square-list1 (cdr items)))))
(define (square-list2 items)
	(map square items))
(define (square-list-test)
	(equal? (square-list (list 1 2 3 4 5)) (list 1 4 9 16 25)))

(define square-list square-list1)
(display (square-list-test))
(newline)
(define square-list square-list2)
(display (square-list-test))
(newline)
