(define (make-from-mag-ang r a)
	(define (dispatch op)
		(cond ((eq? op 'real-part) (* r (cos a)))
			  ((eq? op 'imag-part) (* r (sin a)))
			  ((eq? op 'magnitude) r)
			  ((eq? op 'angle) a)
			  (else
			  	(error "Unknown op -- MAKE-FROM-MAG-ANG" op))))
	dispatch)
(define (apply-generic op arg) (arg op))
(define (real-part z) (apply-generic 'real-part z))
(define (imag-part z) (apply-generic 'imag-part z))
(define (magnitude z) (apply-generic 'magnitude z))
(define (angle z) (apply-generic 'angle z))

;test
(define complex1 (make-from-mag-ang 10 90))
(display (real-part complex1))
(newline)
(display (imag-part complex1))
(newline)
(display (magnitude complex1))
(newline)
(display (angle complex1))
(newline)
