;(a)
;事業所を型と見なし、従業員ファイルに事業所型のタグをつけるべき
;各事業では、get-recordを実装する
(load "./data-driven.scm")
(define (get-record file employee)
	((get 'get-record (type-tag file)) (contents file) employee))
; apply-genericが正しく動かなかった(employeeがタグ付けされていないので)
;	(apply-generic 'get-record file employee))

(define (install-division-A-package)
	(define (dummy-file)
		'((john 500) (mike 200)))
	(define (divA-get-record file employee)
		(if (null? file)
			'()
			(if (eq? (divA-get-name (car file)) employee)
				(car file)
				(divA-get-record (cdr file) employee))))
	(define (divA-get-name record)
		(car record))
	(define (divA-get-salary record)
		(cadr record))
	(define (tag x) (attach-tag 'division-A x))
	(put 'get-file 'division-A (lambda () (tag (dummy-file))))
	(put 'get-record 'division-A (lambda (x y) (tag (divA-get-record x y))))
	(put 'get-salary '(division-A) divA-get-salary)
	)
(define (install-division-B-package)
	(define (dummy-file)
		'((500 tanaka) (200 yamda)))
	(define (divB-get-record file employee)
		(if (null? file)
			'()
			(if (eq? (divB-get-name (car file)) employee)
				(car file)
				(divB-get-record (cdr file) employee))))
	(define (divB-get-name record)
		(cadr record))
	(define (divB-get-salary record)
		(car record))
	(define (tag x) (attach-tag 'division-B x))
	(put 'get-file 'division-B (lambda () (tag (dummy-file))))
	(put 'get-record 'division-B (lambda (x y) (tag (divB-get-record x y))))
	(put 'get-salary '(division-B) divB-get-salary)
	)

;(b)
;get-recordで取得されたレコードは事業所のタグが付けられているべき
(define (get-salary record)
	(apply-generic 'get-salary record))

;(c)
(load "./filter.scm")
(define (find-employee-records files employee-name)
	(filter
		(lambda (x) (not (null? x)))
		(map (lambda (x) (get-record x employee-name)) files)))

;(d)
;新しい事業所の型を作成し、get-record、get-salaryなどの手続きを実装すればよい

;test
(install-division-A-package)
(install-division-B-package)
(define division-A-file ((get 'get-file 'division-A)))
(define division-B-file ((get 'get-file 'division-B)))
(define all-files (list division-A-file division-B-file))
(display (get-record division-A-file 'john))
(newline)
(display (get-salary (get-record division-A-file 'john)))
(newline)
(display (find-employee-records all-files 'tanaka))
(newline)
