(define (make-monitored f)
	(define count 0)
	(define (apply-func arg1)
		(begin (set! count (+ count 1))
			   (f arg1)))
	(define (how-many-calls?) count)
	(define (dispatch m)
		(cond ((eq? m 'how-many-calls?) (how-many-calls?))
			  (else (apply-func m))))
		dispatch)

(define s (make-monitored sqrt))
(display (s 100))
(newline)
(display (s 4))
(newline)
(display (s 'how-many-calls?))
