(load "./queue.scm")

(define (print-queue queue)
	(define (iter l)
		(if (null? l)
			(newline)
			(begin
				(display (car l))
				(iter (cdr l)))))
	(iter (front-ptr queue)))
(define q1 (make-queue))
(print-queue q1)
(insert-queue! q1 'a)
(print-queue q1)
(insert-queue! q1 'b)
(print-queue q1)
(insert-queue! q1 'c)
(print-queue q1)
(delete-queue! q1)
(print-queue q1)
(delete-queue! q1)
(print-queue q1)
(delete-queue! q1)
(print-queue q1)
