(define (make-account balance password)
	(define (withdraw amount)
		(if (>= balance amount)
			(begin (set! balance (- balance amount))
					balance)
			"Insufficient funds"))
	(define (deposit amount)
		(set! balance (+ balance amount))
		balance)
	(define (call-the-cops) (error "i'm a cop"))
	(define fail-count 0)
	(define (dispatch p m)
		(if (eq? p password)
			(begin (set! fail-count 0)
				(cond ((eq? m 'withdraw) withdraw)
					  ((eq? m 'deposit) deposit)
					  (else (error "Unknown request -- MAKE-ACCOUNT"
					  				m))))
			(if (< fail-count 7)
				(begin (set! fail-count (+ fail-count 1)) (error "Incorrect password"))
				(call-the-cops))))
	dispatch)
